CREATE TABLE IF NOT EXISTS todo (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT NOT NULL DEFAULT 'new item',
	done INTEGER NOT NULL DEFAULT 0,
	created NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated NOT NULL DEFAULT CURRENT_TIMESTAMP
)